### ISSUE TITLE
Adafruit BusDevice error when reading anything

### ISSUE THREAD

**Issue by Faeranne** [fourstix/Sparkfun_CircuitPython_QwiicTwist#5]
Looks like Adafruit I2C Device class no longer supports `stop` in write functions.  Needs to be removed.  Will look at a pull request as soon as testing is successful.

**Comment by fivesixzero** [comment]
Ran into this today while testing a Qwiic Twist with CircuitPython.

```
>>> qwiic_rot.version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sparkfun_qwiictwist.py", line 122, in version
  File "sparkfun_qwiictwist.py", line 363, in _read_register16
TypeError: unexpected keyword argument 'stop'
```

This should be pretty easy to fix by changing `_read_register8` and `_read_register16` to use `write_then_readinto`. There are lots of examples of this kind of change in the mentions on this issue:

https://github.com/adafruit/circuitpython/issues/2082

I've got some time today so I'll take a stab at it and see how it goes.

**Comment by fivesixzero** [comment]
I guess it went pretty well! The PR should fix things. :D
